name: Snyk container scan

on:
  push:
    branches: [ main ]

jobs:
  snyk-pipeline:
    name: Build - Push - Snyk Container Scans
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_NAME: hezro/${{ github.event.repository.name }}:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      # Authenticate to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build our container image
      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${IMAGE_NAME}
      
      # Push the image to Dockerhub 
      - name: Push docker image
        run: docker image push ${IMAGE_NAME}
      
      # Download Snyk using wget. 
      # Alternatively you can also install Snyk CLI with npm:
      #    npm install -g snyk
      - name: Download Snyk
        run: |
          wget -O snyk https://static.snyk.io/cli/latest/snyk-linux
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/
          
      # Associate the Snyk CLI with your Snyk account
      - name: Authenticate Snyk
        run: snyk auth ${SNYK_TOKEN}
        
      # Monitor the container
      - name: Scan CLI container scan
        run: snyk container monitor ${IMAGE_NAME} --app-vulns

      # Run a snyk container test
      - name: Snyk Container Test
        run: snyk container test ${IMAGE_NAME} --username=${DOCKERHUB_USER} --password=${DOCKERHUB_TOKEN}
        continue-on-error: true  
